# Copyright (c) 2016, 2020, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

module OCI
  module Cims::Models
    AVAILABILITY_DOMAIN_ENUM = [
      AVAILABILITY_DOMAIN_DEV_1 = 'DEV_1'.freeze,
      AVAILABILITY_DOMAIN_DEV_2 = 'DEV_2'.freeze,
      AVAILABILITY_DOMAIN_DEV_3 = 'DEV_3'.freeze,
      AVAILABILITY_DOMAIN_INTEG_NEXT_1 = 'INTEG_NEXT_1'.freeze,
      AVAILABILITY_DOMAIN_INTEG_STABLE_1 = 'INTEG_STABLE_1'.freeze,
      AVAILABILITY_DOMAIN_SEA_AD_1 = 'SEA_AD_1'.freeze,
      AVAILABILITY_DOMAIN_SEA_AD_2 = 'SEA_AD_2'.freeze,
      AVAILABILITY_DOMAIN_SEA_AD_3 = 'SEA_AD_3'.freeze,
      AVAILABILITY_DOMAIN_PHX_AD_1 = 'PHX_AD_1'.freeze,
      AVAILABILITY_DOMAIN_PHX_AD_2 = 'PHX_AD_2'.freeze,
      AVAILABILITY_DOMAIN_PHX_AD_3 = 'PHX_AD_3'.freeze,
      AVAILABILITY_DOMAIN_US_ASHBURN_AD_1 = 'US_ASHBURN_AD_1'.freeze,
      AVAILABILITY_DOMAIN_US_ASHBURN_AD_2 = 'US_ASHBURN_AD_2'.freeze,
      AVAILABILITY_DOMAIN_US_ASHBURN_AD_3 = 'US_ASHBURN_AD_3'.freeze,
      AVAILABILITY_DOMAIN_US_ASHBURN_AD_4 = 'US_ASHBURN_AD_4'.freeze,
      AVAILABILITY_DOMAIN_EU_FRANKFURT_1_AD_1 = 'EU_FRANKFURT_1_AD_1'.freeze,
      AVAILABILITY_DOMAIN_EU_FRANKFURT_1_AD_2 = 'EU_FRANKFURT_1_AD_2'.freeze,
      AVAILABILITY_DOMAIN_EU_FRANKFURT_1_AD_3 = 'EU_FRANKFURT_1_AD_3'.freeze,
      AVAILABILITY_DOMAIN_UK_LONDON_1_AD_1 = 'UK_LONDON_1_AD_1'.freeze,
      AVAILABILITY_DOMAIN_UK_LONDON_1_AD_2 = 'UK_LONDON_1_AD_2'.freeze,
      AVAILABILITY_DOMAIN_UK_LONDON_1_AD_3 = 'UK_LONDON_1_AD_3'.freeze,
      AVAILABILITY_DOMAIN_CA_TORONTO_1_AD_1 = 'CA_TORONTO_1_AD_1'.freeze,
      AVAILABILITY_DOMAIN_AP_TOKYO_1_AD_1 = 'AP_TOKYO_1_AD_1'.freeze,
      AVAILABILITY_DOMAIN_AP_SEOUL_1_AD_1 = 'AP_SEOUL_1_AD_1'.freeze,
      AVAILABILITY_DOMAIN_AP_MUMBAI_1_AD_1 = 'AP_MUMBAI_1_AD_1'.freeze,
      AVAILABILITY_DOMAIN_SA_SAOPAULO_1_AD_1 = 'SA_SAOPAULO_1_AD_1'.freeze,
      AVAILABILITY_DOMAIN_ME_JEDDAH_1_AD_1 = 'ME_JEDDAH_1_AD_1'.freeze,
      AVAILABILITY_DOMAIN_AP_OSAKA_1_AD_1 = 'AP_OSAKA_1_AD_1'.freeze,
      AVAILABILITY_DOMAIN_AP_SYDNEY_1_AD_1 = 'AP_SYDNEY_1_AD_1'.freeze,
      AVAILABILITY_DOMAIN_EU_ZURICH_1_AD_1 = 'EU_ZURICH_1_AD_1'.freeze,
      AVAILABILITY_DOMAIN_EU_AMSTERDAM_1_AD_1 = 'EU_AMSTERDAM_1_AD_1'.freeze,
      AVAILABILITY_DOMAIN_AP_MELBOURNE_1_AD_1 = 'AP_MELBOURNE_1_AD_1'.freeze,
      AVAILABILITY_DOMAIN_CA_MONTREAL_1_AD_1 = 'CA_MONTREAL_1_AD_1'.freeze,
      AVAILABILITY_DOMAIN_AP_HYDERABAD_1_AD_1 = 'AP_HYDERABAD_1_AD_1'.freeze,
      AVAILABILITY_DOMAIN_AP_CHUNCHEON_1_AD_1 = 'AP_CHUNCHEON_1_AD_1'.freeze,
      AVAILABILITY_DOMAIN_NO_AD = 'NO_AD'.freeze
    ].freeze
  end
end
