# Copyright (c) 2016, 2024, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20200131

module OCI
  module CloudGuard::Models
    ENTITY_TYPE_ENUM = [
      ENTITY_TYPE_EXTERNAL_IP = 'EXTERNAL_IP'.freeze,
      ENTITY_TYPE_INTERNAL_IP = 'INTERNAL_IP'.freeze,
      ENTITY_TYPE_TEXT = 'TEXT'.freeze,
      ENTITY_TYPE_JSON_LIST = 'JSON_LIST'.freeze
    ].freeze
  end
end
