# Copyright (c) 2016, 2022, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

module OCI
  module GoldenGate::Models
    OPERATION_TYPE_ENUM = [
      OPERATION_TYPE_GOLDENGATE_DATABASE_REGISTRATION_CREATE = 'GOLDENGATE_DATABASE_REGISTRATION_CREATE'.freeze,
      OPERATION_TYPE_GOLDENGATE_DATABASE_REGISTRATION_UPDATE = 'GOLDENGATE_DATABASE_REGISTRATION_UPDATE'.freeze,
      OPERATION_TYPE_GOLDENGATE_DATABASE_REGISTRATION_DELETE = 'GOLDENGATE_DATABASE_REGISTRATION_DELETE'.freeze,
      OPERATION_TYPE_GOLDENGATE_DATABASE_REGISTRATION_MOVE = 'GOLDENGATE_DATABASE_REGISTRATION_MOVE'.freeze,
      OPERATION_TYPE_GOLDENGATE_DEPLOYMENT_CREATE = 'GOLDENGATE_DEPLOYMENT_CREATE'.freeze,
      OPERATION_TYPE_GOLDENGATE_DEPLOYMENT_UPDATE = 'GOLDENGATE_DEPLOYMENT_UPDATE'.freeze,
      OPERATION_TYPE_GOLDENGATE_DEPLOYMENT_DELETE = 'GOLDENGATE_DEPLOYMENT_DELETE'.freeze,
      OPERATION_TYPE_GOLDENGATE_DEPLOYMENT_MOVE = 'GOLDENGATE_DEPLOYMENT_MOVE'.freeze,
      OPERATION_TYPE_GOLDENGATE_DEPLOYMENT_RESTORE = 'GOLDENGATE_DEPLOYMENT_RESTORE'.freeze,
      OPERATION_TYPE_GOLDENGATE_DEPLOYMENT_START = 'GOLDENGATE_DEPLOYMENT_START'.freeze,
      OPERATION_TYPE_GOLDENGATE_DEPLOYMENT_STOP = 'GOLDENGATE_DEPLOYMENT_STOP'.freeze,
      OPERATION_TYPE_GOLDENGATE_DEPLOYMENT_PATCH = 'GOLDENGATE_DEPLOYMENT_PATCH'.freeze,
      OPERATION_TYPE_GOLDENGATE_DEPLOYMENT_UPGRADE = 'GOLDENGATE_DEPLOYMENT_UPGRADE'.freeze,
      OPERATION_TYPE_GOLDENGATE_DEPLOYMENT_BACKUP_CREATE = 'GOLDENGATE_DEPLOYMENT_BACKUP_CREATE'.freeze,
      OPERATION_TYPE_GOLDENGATE_DEPLOYMENT_BACKUP_DELETE = 'GOLDENGATE_DEPLOYMENT_BACKUP_DELETE'.freeze,
      OPERATION_TYPE_GOLDENGATE_DEPLOYMENT_BACKUP_CANCEL = 'GOLDENGATE_DEPLOYMENT_BACKUP_CANCEL'.freeze
    ].freeze
  end
end
