# Copyright (c) 2016, 2022, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

module OCI
  module Marketplace::Models
    INELIGIBILITY_REASON_ENUM_ENUM = [
      INELIGIBILITY_REASON_ENUM_INELIGIBLE_ACCOUNT_COUNTRY = 'INELIGIBLE_ACCOUNT_COUNTRY'.freeze,
      INELIGIBILITY_REASON_ENUM_INELIGIBLE_REGION = 'INELIGIBLE_REGION'.freeze,
      INELIGIBILITY_REASON_ENUM_INELIGIBLE_ACCOUNT_BLACKLISTED = 'INELIGIBLE_ACCOUNT_BLACKLISTED'.freeze,
      INELIGIBILITY_REASON_ENUM_INELIGIBLE_ACCOUNT_FEATURE_DISABLED = 'INELIGIBLE_ACCOUNT_FEATURE_DISABLED'.freeze,
      INELIGIBILITY_REASON_ENUM_INELIGIBLE_ACCOUNT_CURRENCY = 'INELIGIBLE_ACCOUNT_CURRENCY'.freeze,
      INELIGIBILITY_REASON_ENUM_INELIGIBLE_ACCOUNT_NOT_PAID = 'INELIGIBLE_ACCOUNT_NOT_PAID'.freeze,
      INELIGIBILITY_REASON_ENUM_INELIGIBLE_ACCOUNT_INTERNAL = 'INELIGIBLE_ACCOUNT_INTERNAL'.freeze,
      INELIGIBILITY_REASON_ENUM_INELIGIBLE_ACCOUNT_GOV_SUBSCRIPTION = 'INELIGIBLE_ACCOUNT_GOV_SUBSCRIPTION'.freeze,
      INELIGIBILITY_REASON_ENUM_INELIGIBLE_PAID_LISTING_THROTTLED = 'INELIGIBLE_PAID_LISTING_THROTTLED'.freeze,
      INELIGIBILITY_REASON_ENUM_NOT_AUTHORIZED = 'NOT_AUTHORIZED'.freeze
    ].freeze
  end
end
