# Copyright (c) 2016, 2024, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20221208

module OCI
  module ComputeCloudAtCustomer
    # Module containing models for requests made to, and responses received from,
    # OCI ComputeCloudAtCustomer services
    module Models
    end
  end
end

# Require models
require 'oci/compute_cloud_at_customer/models/ccc_infrastructure'
require 'oci/compute_cloud_at_customer/models/ccc_infrastructure_collection'
require 'oci/compute_cloud_at_customer/models/ccc_infrastructure_inventory'
require 'oci/compute_cloud_at_customer/models/ccc_infrastructure_management_node'
require 'oci/compute_cloud_at_customer/models/ccc_infrastructure_network_configuration'
require 'oci/compute_cloud_at_customer/models/ccc_infrastructure_routing_dynamic_details'
require 'oci/compute_cloud_at_customer/models/ccc_infrastructure_routing_static_details'
require 'oci/compute_cloud_at_customer/models/ccc_infrastructure_summary'
require 'oci/compute_cloud_at_customer/models/ccc_schedule_event'
require 'oci/compute_cloud_at_customer/models/ccc_upgrade_information'
require 'oci/compute_cloud_at_customer/models/ccc_upgrade_schedule'
require 'oci/compute_cloud_at_customer/models/ccc_upgrade_schedule_collection'
require 'oci/compute_cloud_at_customer/models/ccc_upgrade_schedule_summary'
require 'oci/compute_cloud_at_customer/models/change_ccc_infrastructure_compartment_details'
require 'oci/compute_cloud_at_customer/models/change_ccc_upgrade_schedule_compartment_details'
require 'oci/compute_cloud_at_customer/models/create_ccc_infrastructure_details'
require 'oci/compute_cloud_at_customer/models/create_ccc_schedule_event'
require 'oci/compute_cloud_at_customer/models/create_ccc_upgrade_schedule_details'
require 'oci/compute_cloud_at_customer/models/peer_information'
require 'oci/compute_cloud_at_customer/models/sort_order'
require 'oci/compute_cloud_at_customer/models/update_ccc_infrastructure_details'
require 'oci/compute_cloud_at_customer/models/update_ccc_schedule_event'
require 'oci/compute_cloud_at_customer/models/update_ccc_upgrade_schedule_details'

# Require generated clients
require 'oci/compute_cloud_at_customer/compute_cloud_at_customer_client'
require 'oci/compute_cloud_at_customer/compute_cloud_at_customer_client_composite_operations'

# Require service utilities
require 'oci/compute_cloud_at_customer/util'
