# Copyright (c) 2016, 2022, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

module OCI
  module OperatorAccessControl::Models
    ACCESS_REQUEST_LIFECYCLE_STATES_ENUM = [
      ACCESS_REQUEST_LIFECYCLE_STATES_CREATED = 'CREATED'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_APPROVALWAITING = 'APPROVALWAITING'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_PREAPPROVED = 'PREAPPROVED'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_APPROVED = 'APPROVED'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_REJECTED = 'REJECTED'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_DEPLOYED = 'DEPLOYED'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_DEPLOYFAILED = 'DEPLOYFAILED'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_UNDEPLOYED = 'UNDEPLOYED'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_UNDEPLOYFAILED = 'UNDEPLOYFAILED'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_CLOSEFAILED = 'CLOSEFAILED'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_REVOKEFAILED = 'REVOKEFAILED'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_EXPIRYFAILED = 'EXPIRYFAILED'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_REVOKING = 'REVOKING'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_REVOKED = 'REVOKED'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_EXTENDING = 'EXTENDING'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_EXTENDED = 'EXTENDED'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_EXTENSIONREJECTED = 'EXTENSIONREJECTED'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_COMPLETING = 'COMPLETING'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_COMPLETED = 'COMPLETED'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_EXPIRED = 'EXPIRED'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_APPROVEDFORFUTURE = 'APPROVEDFORFUTURE'.freeze,
      ACCESS_REQUEST_LIFECYCLE_STATES_INREVIEW = 'INREVIEW'.freeze
    ].freeze
  end
end
