# Copyright (c) 2016, 2022, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

require 'oci/common'

# Top level module for the Oracle Cloud Infrastructure SDK
module OCI
  autoload :AiAnomalyDetection,           'oci/ai_anomaly_detection/ai_anomaly_detection'
  autoload :AiLanguage,                   'oci/ai_language/ai_language'
  autoload :AiVision,                     'oci/ai_vision/ai_vision'
  autoload :Analytics,                    'oci/analytics/analytics'
  autoload :AnnouncementsService,         'oci/announcements_service/announcements_service'
  autoload :Apigateway,                   'oci/apigateway/apigateway'
  autoload :ApmConfig,                    'oci/apm_config/apm_config'
  autoload :ApmControlPlane,              'oci/apm_control_plane/apm_control_plane'
  autoload :ApmSynthetics,                'oci/apm_synthetics/apm_synthetics'
  autoload :ApmTraces,                    'oci/apm_traces/apm_traces'
  autoload :ApplicationMigration,         'oci/application_migration/application_migration'
  autoload :AppmgmtControl,               'oci/appmgmt_control/appmgmt_control'
  autoload :Artifacts,                    'oci/artifacts/artifacts'
  autoload :Audit,                        'oci/audit/audit'
  autoload :Auth,                         'oci/auth/auth'
  autoload :Autoscaling,                  'oci/autoscaling/autoscaling'
  autoload :Bastion,                      'oci/bastion/bastion'
  autoload :Bds,                          'oci/bds/bds'
  autoload :Blockchain,                   'oci/blockchain/blockchain'
  autoload :Budget,                       'oci/budget/budget'
  autoload :Certificates,                 'oci/certificates/certificates'
  autoload :CertificatesManagement,       'oci/certificates_management/certificates_management'
  autoload :Cims,                         'oci/cims/cims'
  autoload :CloudGuard,                   'oci/cloud_guard/cloud_guard'
  autoload :ComputeInstanceAgent,         'oci/compute_instance_agent/compute_instance_agent'
  autoload :ContainerEngine,              'oci/container_engine/container_engine'
  autoload :Core,                         'oci/core/core'
  autoload :DashboardService,             'oci/dashboard_service/dashboard_service'
  autoload :DataCatalog,                  'oci/data_catalog/data_catalog'
  autoload :DataFlow,                     'oci/data_flow/data_flow'
  autoload :DataIntegration,              'oci/data_integration/data_integration'
  autoload :DataLabelingService,          'oci/data_labeling_service/data_labeling_service'
  autoload :DataLabelingServiceDataplane, 'oci/data_labeling_service_dataplane/data_labeling_service_dataplane'
  autoload :DataSafe,                     'oci/data_safe/data_safe'
  autoload :DataScience,                  'oci/data_science/data_science'
  autoload :Database,                     'oci/database/database'
  autoload :DatabaseManagement,           'oci/database_management/database_management'
  autoload :DatabaseMigration,            'oci/database_migration/database_migration'
  autoload :DatabaseTools,                'oci/database_tools/database_tools'
  autoload :Devops,                       'oci/devops/devops'
  autoload :Dns,                          'oci/dns/dns'
  autoload :Dts,                          'oci/dts/dts'
  autoload :Email,                        'oci/email/email'
  autoload :Events,                       'oci/events/events'
  autoload :FileStorage,                  'oci/file_storage/file_storage'
  autoload :Functions,                    'oci/functions/functions'
  autoload :GenericArtifactsContent,      'oci/generic_artifacts_content/generic_artifacts_content'
  autoload :GoldenGate,                   'oci/golden_gate/golden_gate'
  autoload :Healthchecks,                 'oci/healthchecks/healthchecks'
  autoload :Identity,                     'oci/identity/identity'
  autoload :IdentityDataPlane,            'oci/identity_data_plane/identity_data_plane'
  autoload :Integration,                  'oci/integration/integration'
  autoload :Internal,                     'oci/internal/internal'
  autoload :Jms,                          'oci/jms/jms'
  autoload :KeyManagement,                'oci/key_management/key_management'
  autoload :Limits,                       'oci/limits/limits'
  autoload :LoadBalancer,                 'oci/load_balancer/load_balancer'
  autoload :LogAnalytics,                 'oci/log_analytics/log_analytics'
  autoload :Logging,                      'oci/logging/logging'
  autoload :Loggingingestion,             'oci/loggingingestion/loggingingestion'
  autoload :Loggingsearch,                'oci/loggingsearch/loggingsearch'
  autoload :ManagementAgent,              'oci/management_agent/management_agent'
  autoload :ManagementDashboard,          'oci/management_dashboard/management_dashboard'
  autoload :Marketplace,                  'oci/marketplace/marketplace'
  autoload :Monitoring,                   'oci/monitoring/monitoring'
  autoload :Mysql,                        'oci/mysql/mysql'
  autoload :NetworkLoadBalancer,          'oci/network_load_balancer/network_load_balancer'
  autoload :Nosql,                        'oci/nosql/nosql'
  autoload :ObjectStorage,                'oci/object_storage/object_storage'
  autoload :Oce,                          'oci/oce/oce'
  autoload :Ocvp,                         'oci/ocvp/ocvp'
  autoload :Oda,                          'oci/oda/oda'
  autoload :Ons,                          'oci/ons/ons'
  autoload :OperatorAccessControl,        'oci/operator_access_control/operator_access_control'
  autoload :Opsi,                         'oci/opsi/opsi'
  autoload :Optimizer,                    'oci/optimizer/optimizer'
  autoload :OsManagement,                 'oci/os_management/os_management'
  autoload :OspGateway,                   'oci/osp_gateway/osp_gateway'
  autoload :OsubBillingSchedule,          'oci/osub_billing_schedule/osub_billing_schedule'
  autoload :OsubOrganizationSubscription, 'oci/osub_organization_subscription/osub_organization_subscription'
  autoload :OsubSubscription,             'oci/osub_subscription/osub_subscription'
  autoload :OsubUsage,                    'oci/osub_usage/osub_usage'
  autoload :ResourceManager,              'oci/resource_manager/resource_manager'
  autoload :ResourceSearch,               'oci/resource_search/resource_search'
  autoload :Retry,                        'oci/retry/retry'
  autoload :Rover,                        'oci/rover/rover'
  autoload :Sch,                          'oci/sch/sch'
  autoload :Secrets,                      'oci/secrets/secrets'
  autoload :ServiceCatalog,               'oci/service_catalog/service_catalog'
  autoload :ServiceManagerProxy,          'oci/service_manager_proxy/service_manager_proxy'
  autoload :Streaming,                    'oci/streaming/streaming'
  autoload :TenantManagerControlPlane,    'oci/tenant_manager_control_plane/tenant_manager_control_plane'
  autoload :ThreatIntelligence,           'oci/threat_intelligence/threat_intelligence'
  autoload :Usage,                        'oci/usage/usage'
  autoload :UsageApi,                     'oci/usage_api/usage_api'
  autoload :Vault,                        'oci/vault/vault'
  autoload :VisualBuilder,                'oci/visual_builder/visual_builder'
  autoload :VulnerabilityScanning,        'oci/vulnerability_scanning/vulnerability_scanning'
  autoload :Waas,                         'oci/waas/waas'
  autoload :Waf,                          'oci/waf/waf'
  autoload :WorkRequests,                 'oci/work_requests/work_requests'

  class << self
  end
end

OracleBMC = OCI
