# Copyright (c) 2016, 2020, Oracle and/or its affiliates. All rights reserved.

module OCI
  module Analytics::Models
    ANALYTICS_INSTANCE_LIFECYCLE_STATE_ENUM = [
      ANALYTICS_INSTANCE_LIFECYCLE_STATE_ACTIVE = 'ACTIVE'.freeze,
      ANALYTICS_INSTANCE_LIFECYCLE_STATE_CREATING = 'CREATING'.freeze,
      ANALYTICS_INSTANCE_LIFECYCLE_STATE_DELETED = 'DELETED'.freeze,
      ANALYTICS_INSTANCE_LIFECYCLE_STATE_DELETING = 'DELETING'.freeze,
      ANALYTICS_INSTANCE_LIFECYCLE_STATE_FAILED = 'FAILED'.freeze,
      ANALYTICS_INSTANCE_LIFECYCLE_STATE_INACTIVE = 'INACTIVE'.freeze,
      ANALYTICS_INSTANCE_LIFECYCLE_STATE_UPDATING = 'UPDATING'.freeze
    ].freeze
  end
end
