# Copyright (c) 2016, 2022, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

module OCI
  module DatabaseTools::Models
    OPERATION_TYPE_ENUM = [
      OPERATION_TYPE_CREATE_DATABASE_TOOLS_CONNECTION = 'CREATE_DATABASE_TOOLS_CONNECTION'.freeze,
      OPERATION_TYPE_UPDATE_DATABASE_TOOLS_CONNECTION = 'UPDATE_DATABASE_TOOLS_CONNECTION'.freeze,
      OPERATION_TYPE_DELETE_DATABASE_TOOLS_CONNECTION = 'DELETE_DATABASE_TOOLS_CONNECTION'.freeze,
      OPERATION_TYPE_CREATE_DATABASE_TOOLS_SERVICE_INSTANCE = 'CREATE_DATABASE_TOOLS_SERVICE_INSTANCE'.freeze,
      OPERATION_TYPE_UPDATE_DATABASE_TOOLS_SERVICE_INSTANCE = 'UPDATE_DATABASE_TOOLS_SERVICE_INSTANCE'.freeze,
      OPERATION_TYPE_DELETE_DATABASE_TOOLS_SERVICE_INSTANCE = 'DELETE_DATABASE_TOOLS_SERVICE_INSTANCE'.freeze,
      OPERATION_TYPE_CREATE_DATABASE_TOOLS_PRIVATE_ENDPOINT = 'CREATE_DATABASE_TOOLS_PRIVATE_ENDPOINT'.freeze,
      OPERATION_TYPE_UPDATE_DATABASE_TOOLS_PRIVATE_ENDPOINT = 'UPDATE_DATABASE_TOOLS_PRIVATE_ENDPOINT'.freeze,
      OPERATION_TYPE_DELETE_DATABASE_TOOLS_PRIVATE_ENDPOINT = 'DELETE_DATABASE_TOOLS_PRIVATE_ENDPOINT'.freeze
    ].freeze
  end
end
