# Copyright (c) 2016, 2020, Oracle and/or its affiliates. All rights reserved.

module OCI
  module ApplicationMigration::Models
    MIGRATION_STATES_ENUM = [
      MIGRATION_STATES_DISCOVERING_APPLICATION = 'DISCOVERING_APPLICATION'.freeze,
      MIGRATION_STATES_DISCOVERY_FAILED = 'DISCOVERY_FAILED'.freeze,
      MIGRATION_STATES_MISSING_CONFIG_VALUES = 'MISSING_CONFIG_VALUES'.freeze,
      MIGRATION_STATES_READY = 'READY'.freeze,
      MIGRATION_STATES_MIGRATING = 'MIGRATING'.freeze,
      MIGRATION_STATES_MIGRATION_FAILED = 'MIGRATION_FAILED'.freeze,
      MIGRATION_STATES_MIGRATION_SUCCEEDED = 'MIGRATION_SUCCEEDED'.freeze
    ].freeze
  end
end
