# Copyright (c) 2016, 2023, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20220518

module OCI
  module AccessGovernanceCp::Models
    INSTANCE_LIFECYCLE_STATE_ENUM = [
      INSTANCE_LIFECYCLE_STATE_CREATING = 'CREATING'.freeze,
      INSTANCE_LIFECYCLE_STATE_ACTIVE = 'ACTIVE'.freeze,
      INSTANCE_LIFECYCLE_STATE_DELETING = 'DELETING'.freeze,
      INSTANCE_LIFECYCLE_STATE_DELETED = 'DELETED'.freeze,
      INSTANCE_LIFECYCLE_STATE_NEEDS_ATTENTION = 'NEEDS_ATTENTION'.freeze
    ].freeze
  end
end
