# Copyright (c) 2016, 2024, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20220915

module OCI
  module Psql::Models
    OPERATION_TYPE_ENUM = [
      OPERATION_TYPE_CREATE_POSTGRESQL_DB_SYSTEM = 'CREATE_POSTGRESQL_DB_SYSTEM'.freeze,
      OPERATION_TYPE_UPDATE_POSTGRESQL_DB_SYSTEM = 'UPDATE_POSTGRESQL_DB_SYSTEM'.freeze,
      OPERATION_TYPE_DELETE_POSTGRESQL_DB_SYSTEM = 'DELETE_POSTGRESQL_DB_SYSTEM'.freeze,
      OPERATION_TYPE_MOVE_POSTGRESQL_DB_SYSTEM = 'MOVE_POSTGRESQL_DB_SYSTEM'.freeze,
      OPERATION_TYPE_CREATE_POSTGRESQL_DB_SYSTEM_BACKUP = 'CREATE_POSTGRESQL_DB_SYSTEM_BACKUP'.freeze,
      OPERATION_TYPE_UPDATE_POSTGRESQL_DB_SYSTEM_BACKUP = 'UPDATE_POSTGRESQL_DB_SYSTEM_BACKUP'.freeze,
      OPERATION_TYPE_DELETE_POSTGRESQL_DB_SYSTEM_BACKUP = 'DELETE_POSTGRESQL_DB_SYSTEM_BACKUP'.freeze,
      OPERATION_TYPE_MOVE_POSTGRESQL_DB_SYSTEM_BACKUP = 'MOVE_POSTGRESQL_DB_SYSTEM_BACKUP'.freeze
    ].freeze
  end
end
