# Copyright (c) 2016, 2021, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

module OCI
  module Opsi::Models
    OPERATION_TYPE_ENUM = [
      OPERATION_TYPE_ENABLE_DATABASE_INSIGHT = 'ENABLE_DATABASE_INSIGHT'.freeze,
      OPERATION_TYPE_DISABLE_DATABASE_INSIGHT = 'DISABLE_DATABASE_INSIGHT'.freeze,
      OPERATION_TYPE_UPDATE_DATABASE_INSIGHT = 'UPDATE_DATABASE_INSIGHT'.freeze,
      OPERATION_TYPE_CREATE_DATABASE_INSIGHT = 'CREATE_DATABASE_INSIGHT'.freeze,
      OPERATION_TYPE_MOVE_DATABASE_INSIGHT = 'MOVE_DATABASE_INSIGHT'.freeze,
      OPERATION_TYPE_DELETE_DATABASE_INSIGHT = 'DELETE_DATABASE_INSIGHT'.freeze,
      OPERATION_TYPE_CREATE_ENTERPRISE_MANAGER_BRIDGE = 'CREATE_ENTERPRISE_MANAGER_BRIDGE'.freeze,
      OPERATION_TYPE_UDPATE_ENTERPRISE_MANAGER_BRIDGE = 'UDPATE_ENTERPRISE_MANAGER_BRIDGE'.freeze,
      OPERATION_TYPE_MOVE_ENTERPRISE_MANAGER_BRIDGE = 'MOVE_ENTERPRISE_MANAGER_BRIDGE'.freeze,
      OPERATION_TYPE_DELETE_ENTERPRISE_MANAGER_BRIDGE = 'DELETE_ENTERPRISE_MANAGER_BRIDGE'.freeze,
      OPERATION_TYPE_ENABLE_HOST_INSIGHT = 'ENABLE_HOST_INSIGHT'.freeze,
      OPERATION_TYPE_DISABLE_HOST_INSIGHT = 'DISABLE_HOST_INSIGHT'.freeze,
      OPERATION_TYPE_UPDATE_HOST_INSIGHT = 'UPDATE_HOST_INSIGHT'.freeze,
      OPERATION_TYPE_CREATE_HOST_INSIGHT = 'CREATE_HOST_INSIGHT'.freeze,
      OPERATION_TYPE_MOVE_HOST_INSIGHT = 'MOVE_HOST_INSIGHT'.freeze,
      OPERATION_TYPE_DELETE_HOST_INSIGHT = 'DELETE_HOST_INSIGHT'.freeze
    ].freeze
  end
end
