# Copyright (c) 2016, 2022, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

module OCI
  module Opsi::Models
    OPERATION_TYPE_ENUM = [
      OPERATION_TYPE_ENABLE_DATABASE_INSIGHT = 'ENABLE_DATABASE_INSIGHT'.freeze,
      OPERATION_TYPE_DISABLE_DATABASE_INSIGHT = 'DISABLE_DATABASE_INSIGHT'.freeze,
      OPERATION_TYPE_UPDATE_DATABASE_INSIGHT = 'UPDATE_DATABASE_INSIGHT'.freeze,
      OPERATION_TYPE_CREATE_DATABASE_INSIGHT = 'CREATE_DATABASE_INSIGHT'.freeze,
      OPERATION_TYPE_MOVE_DATABASE_INSIGHT = 'MOVE_DATABASE_INSIGHT'.freeze,
      OPERATION_TYPE_DELETE_DATABASE_INSIGHT = 'DELETE_DATABASE_INSIGHT'.freeze,
      OPERATION_TYPE_CREATE_ENTERPRISE_MANAGER_BRIDGE = 'CREATE_ENTERPRISE_MANAGER_BRIDGE'.freeze,
      OPERATION_TYPE_UDPATE_ENTERPRISE_MANAGER_BRIDGE = 'UDPATE_ENTERPRISE_MANAGER_BRIDGE'.freeze,
      OPERATION_TYPE_MOVE_ENTERPRISE_MANAGER_BRIDGE = 'MOVE_ENTERPRISE_MANAGER_BRIDGE'.freeze,
      OPERATION_TYPE_DELETE_ENTERPRISE_MANAGER_BRIDGE = 'DELETE_ENTERPRISE_MANAGER_BRIDGE'.freeze,
      OPERATION_TYPE_ENABLE_HOST_INSIGHT = 'ENABLE_HOST_INSIGHT'.freeze,
      OPERATION_TYPE_DISABLE_HOST_INSIGHT = 'DISABLE_HOST_INSIGHT'.freeze,
      OPERATION_TYPE_UPDATE_HOST_INSIGHT = 'UPDATE_HOST_INSIGHT'.freeze,
      OPERATION_TYPE_CREATE_HOST_INSIGHT = 'CREATE_HOST_INSIGHT'.freeze,
      OPERATION_TYPE_MOVE_HOST_INSIGHT = 'MOVE_HOST_INSIGHT'.freeze,
      OPERATION_TYPE_DELETE_HOST_INSIGHT = 'DELETE_HOST_INSIGHT'.freeze,
      OPERATION_TYPE_CREATE_EXADATA_INSIGHT = 'CREATE_EXADATA_INSIGHT'.freeze,
      OPERATION_TYPE_ENABLE_EXADATA_INSIGHT = 'ENABLE_EXADATA_INSIGHT'.freeze,
      OPERATION_TYPE_DISABLE_EXADATA_INSIGHT = 'DISABLE_EXADATA_INSIGHT'.freeze,
      OPERATION_TYPE_UPDATE_EXADATA_INSIGHT = 'UPDATE_EXADATA_INSIGHT'.freeze,
      OPERATION_TYPE_MOVE_EXADATA_INSIGHT = 'MOVE_EXADATA_INSIGHT'.freeze,
      OPERATION_TYPE_DELETE_EXADATA_INSIGHT = 'DELETE_EXADATA_INSIGHT'.freeze,
      OPERATION_TYPE_ADD_EXADATA_INSIGHT_MEMBERS = 'ADD_EXADATA_INSIGHT_MEMBERS'.freeze,
      OPERATION_TYPE_EXADATA_AUTO_SYNC = 'EXADATA_AUTO_SYNC'.freeze,
      OPERATION_TYPE_UPDATE_OPSI_WAREHOUSE = 'UPDATE_OPSI_WAREHOUSE'.freeze,
      OPERATION_TYPE_CREATE_OPSI_WAREHOUSE = 'CREATE_OPSI_WAREHOUSE'.freeze,
      OPERATION_TYPE_MOVE_OPSI_WAREHOUSE = 'MOVE_OPSI_WAREHOUSE'.freeze,
      OPERATION_TYPE_DELETE_OPSI_WAREHOUSE = 'DELETE_OPSI_WAREHOUSE'.freeze,
      OPERATION_TYPE_ROTATE_OPSI_WAREHOUSE_WALLET = 'ROTATE_OPSI_WAREHOUSE_WALLET'.freeze,
      OPERATION_TYPE_UPDATE_OPSI_WAREHOUSE_USER = 'UPDATE_OPSI_WAREHOUSE_USER'.freeze,
      OPERATION_TYPE_CREATE_OPSI_WAREHOUSE_USER = 'CREATE_OPSI_WAREHOUSE_USER'.freeze,
      OPERATION_TYPE_MOVE_OPSI_WAREHOUSE_USER = 'MOVE_OPSI_WAREHOUSE_USER'.freeze,
      OPERATION_TYPE_DELETE_OPSI_WAREHOUSE_USER = 'DELETE_OPSI_WAREHOUSE_USER'.freeze,
      OPERATION_TYPE_UPDATE_AWRHUB = 'UPDATE_AWRHUB'.freeze,
      OPERATION_TYPE_CREATE_AWRHUB = 'CREATE_AWRHUB'.freeze,
      OPERATION_TYPE_MOVE_AWRHUB = 'MOVE_AWRHUB'.freeze,
      OPERATION_TYPE_DELETE_AWRHUB = 'DELETE_AWRHUB'.freeze
    ].freeze
  end
end
