# Copyright (c) 2016, 2023, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20200202

module OCI
  module ManagementAgent::Models
    MANAGEMENT_AGENT_PLUGIN_GROUP_BY_ENUM = [
      MANAGEMENT_AGENT_PLUGIN_GROUP_BY_PLUGIN_NAME = 'pluginName'.freeze
    ].freeze
  end
end
