# Copyright (c) 2016, 2022, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

module OCI
  module ServiceManagerProxy::Models
    SERVICE_ENTITLEMENT_REGISTRATION_STATUS_ENUM = [
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_INITIALIZED = 'INITIALIZED'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_BEGIN_ACTIVATION = 'BEGIN_ACTIVATION'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_ACTIVE = 'ACTIVE'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_BEGIN_SOFT_TERMINATION = 'BEGIN_SOFT_TERMINATION'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_SOFT_TERMINATED = 'SOFT_TERMINATED'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_BEGIN_TERMINATION = 'BEGIN_TERMINATION'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_CANCELED = 'CANCELED'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_TERMINATED = 'TERMINATED'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_BEGIN_DISABLING = 'BEGIN_DISABLING'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_BEGIN_ENABLING = 'BEGIN_ENABLING'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_BEGIN_MIGRATION = 'BEGIN_MIGRATION'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_DISABLED = 'DISABLED'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_BEGIN_SUSPENSION = 'BEGIN_SUSPENSION'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_BEGIN_RESUMPTION = 'BEGIN_RESUMPTION'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_SUSPENDED = 'SUSPENDED'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_BEGIN_LOCK_RELOCATION = 'BEGIN_LOCK_RELOCATION'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_LOCKED_RELOCATION = 'LOCKED_RELOCATION'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_BEGIN_RELOCATION = 'BEGIN_RELOCATION'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_RELOCATED = 'RELOCATED'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_BEGIN_UNLOCK_RELOCATION = 'BEGIN_UNLOCK_RELOCATION'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_UNLOCKED_RELOCATION = 'UNLOCKED_RELOCATION'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_FAILED_LOCK_RELOCATION = 'FAILED_LOCK_RELOCATION'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_FAILED_ACTIVATION = 'FAILED_ACTIVATION'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_FAILED_MIGRATION = 'FAILED_MIGRATION'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_ACCESS_DISABLED = 'ACCESS_DISABLED'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_BEGIN_DISABLING_ACCESS = 'BEGIN_DISABLING_ACCESS'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_BEGIN_ENABLING_ACCESS = 'BEGIN_ENABLING_ACCESS'.freeze,
      SERVICE_ENTITLEMENT_REGISTRATION_STATUS_TRA_UNKNOWN = 'TRA_UNKNOWN'.freeze
    ].freeze
  end
end
