# Copyright (c) 2016, 2020, Oracle and/or its affiliates. All rights reserved.

module OCI
  module DataScience::Models
    NOTEBOOK_SESSION_LIFECYCLE_STATE_ENUM = [
      NOTEBOOK_SESSION_LIFECYCLE_STATE_CREATING = 'CREATING'.freeze,
      NOTEBOOK_SESSION_LIFECYCLE_STATE_ACTIVE = 'ACTIVE'.freeze,
      NOTEBOOK_SESSION_LIFECYCLE_STATE_DELETING = 'DELETING'.freeze,
      NOTEBOOK_SESSION_LIFECYCLE_STATE_DELETED = 'DELETED'.freeze,
      NOTEBOOK_SESSION_LIFECYCLE_STATE_FAILED = 'FAILED'.freeze,
      NOTEBOOK_SESSION_LIFECYCLE_STATE_INACTIVE = 'INACTIVE'.freeze,
      NOTEBOOK_SESSION_LIFECYCLE_STATE_UPDATING = 'UPDATING'.freeze
    ].freeze
  end
end
