# Copyright (c) 2016, 2019, Oracle and/or its affiliates. All rights reserved.

module OCI
  module Waas::Models
    WORK_REQUEST_STATUS_VALUES_ENUM = [
      WORK_REQUEST_STATUS_VALUES_ACCEPTED = 'ACCEPTED'.freeze,
      WORK_REQUEST_STATUS_VALUES_IN_PROGRESS = 'IN_PROGRESS'.freeze,
      WORK_REQUEST_STATUS_VALUES_FAILED = 'FAILED'.freeze,
      WORK_REQUEST_STATUS_VALUES_SUCCEEDED = 'SUCCEEDED'.freeze,
      WORK_REQUEST_STATUS_VALUES_CANCELING = 'CANCELING'.freeze,
      WORK_REQUEST_STATUS_VALUES_CANCELED = 'CANCELED'.freeze
    ].freeze
  end
end
